export enum Enums {
  ACCOUNT = "account",
  REF_ACCOUNT = "ref_account",
  INVITE_CODE = "invite_code",
  FULLNAME = "fullname",
  NICKNAME = "nickname",
  DOB = "dob",
  GENDER = "gender",
  COUNTRY = "country",
  PHONE = "phone",
  SMS_OTP = "sms_otp",
  EMAIL = "email",
  SNS_ACCOUNT_1 = "sns_account_1",
  SNS_ACCOUNT_2 = "sns_account_2",
  NATIONALITY = "nationality",
  PLACE_OF_BIRTH = "place_of_birth",
  PRESENT_ADDRESS = "present_address",
  PERMANENT_ADDRESS = "permanent_address",
  NATURE_OF_WORK = "nature_of_work",
  SOURCE_OF_INCOME = "source_of_income",
  GAMING_SITE = "gaming_site",
  IS_SUB_AD = "is_sub_ad",
  SELF_EXCLUSION_AT = "self_exclusion_at"
}
